In [1]:
import cv2
import numpy as np

# Load/Read Image

In [2]:
img=cv2.imread('image_examples/Modi.jpg')

In [3]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


# Shape gives the dimensions of the image array

In [4]:
img.shape

(1358, 1500, 3)

In [5]:
#height
int(img.shape[0])

1358

In [6]:
#width
int(img.shape[1])

1500

# Display the image

In [7]:
cv2.imshow('PM',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [8]:
img=cv2.imread('image_examples/Modi.jpg',0)
cv2.imshow('Modi Image',img)
cv2.waitKey()
cv2.destroyAllWindows()

# Save Image

In [9]:
cv2.imwrite('modi_b_w.jpg',img)

True

# Resize Image

In [10]:
img=cv2.imread('image_examples/Modi.jpg')
resized_image=cv2.resize(img,(500,500))
cv2.imshow('Modi Image',resized_image)
cv2.waitKey()
cv2.destroyAllWindows()

# Face Detection Using HAAR Cascade Classifier

In [22]:
# We point OpenCV's CascadeClassifier function to where our 
# classifier (XML file format) is stored
face_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')

# Load our image then convert it to grayscale
image = cv2.imread('image_examples/Modi.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Our classifier returns the ROI of the detected face as a tuple
# It stores the top left coordinate and the bottom right coordiantes
faces = face_classifier.detectMultiScale(gray, 1.3, 5)

# When no faces detected, face_classifier returns and empty tuple
if faces is ():
    print("No faces found")

# We iterate through our faces array and draw a rectangle
# over each face in faces
for (x,y,w,h) in faces:
    cv2.rectangle(image, (x,y), (x+w,y+h), (127,0,255), 2)
    cv2.imshow('Face Detection', image)
    cv2.waitKey(0)
    
cv2.destroyAllWindows()

<>:14: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:14: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-22-3003cc084920>:14: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


# Face & Eye Detection using HAAR Cascade Classifiers in Image

In [23]:
face_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_eye.xml')
 
img = cv2.imread('image_examples/Modi.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray, 1.3, 5)

# When no faces detected, face_classifier returns and empty tuple
if faces is ():
    print("No Face Found")

for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(127,0,255),2)
    cv2.imshow('img',img)
    cv2.waitKey(0)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_classifier.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(255,255,0),2)
        cv2.imshow('img',img)
        cv2.waitKey(0)
    
cv2.destroyAllWindows()

<>:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-23-777c2625cadc>:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


# Capture a video

In [15]:
import cv2
video=cv2.VideoCapture(0)

while True:
    check, frame=video.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow('Video',gray)
    if cv2.waitKey(1)==ord('q'):
        break
video.release()
cv2.destroyAllWindows()

# Pedistrian Detection

In [17]:
body_classifier=cv2.CascadeClassifier('Haarcascades\haarcascade_fullbody.xml')
cap=cv2.VideoCapture('image_examples/walking.avi')
while cap.isOpened():
    ret,frame=cap.read()
    gray=cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    bodies=body_classifier.detectMultiScale(gray,1.2,3)
    
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
        cv2.imshow('Pedestrians',frame)
    if cv2.waitKey(1)==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

# Car Detection

In [18]:
import time

car_classifier=cv2.CascadeClassifier('Haarcascades\haarcascade_car.xml')

cap=cv2.VideoCapture('image_examples/cars.avi')

while cap.isOpened():
    time.sleep(.05)
    ret,frame=cap.read()
    gray=cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    cars=car_classifier.detectMultiScale(gray,1.4,2)
    
    for(x,y,w,h) in cars:
        cv2.rectangle(frame,(x,y),(x+w, y+h),(0,255,255),2)
        cv2.imshow('Cars', frame)
    if cv2.waitKey(1)==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()